name: Update Pages
on:
  workflow_dispatch:

jobs:
  update-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Run Update Script
        run: |
          chmod +x update-pages.sh
          ./update-pages.sh
